# Generated by Django 5.1.1 on 2024-09-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_student_discount_percent_student_final_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='student',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
